name: floater
description: A framework that floats over flutter as a higher level construct to provide architecture and structure for complex flutter apps.
version: 0.1.4+1
homepage: https://github.com/shreymahendru/floater

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.7.0
  get_it: ^7.2.0
  flutter_secure_storage: ^5.0.2
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
